language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - cmake
    - swig
    - libsqlite3-dev
    - python-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install swig python sqlite;
    fi

script:
  - mkdir build && cd build && cmake .. -DBUILD_PYTHON_BINDINGS=ON && make
